mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView, TokenVerifyView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls')),
    path('api/', include('website.api.urls')),

]

website/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenVerifyView, TokenObtainPairView, TokenRefreshView

from . import views

urlpatterns = [
    path('messages', views.get_messages),
    path('message/<str:id>', views.get_message),
    path('message_create', views.create_message),
    path('message/update/<str:id>', views.update_Message),
    path('message/delete/<str:id>', views.delete_Message),
    path('token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),

]

website/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home_index'),
    path('messages', views.all_messages, name='all_messages'),
    path('messages/new', views.new_message, name='new_message'),
    path('messages/edit/<str:id>', views.edit_message, name='edit_message'),
    path('messages/<str:id>', views.show_message, name='show_message'),
    path('messages/delete/<str:id>', views.delete_message, name='delete_message'),
    path('messages/response/add/<str:id>', views.add_response, name='response_message'),
    path('messages/response/edit/<str:id>', views.edit_response, name='edit_response_message'),
    path('messages/response/delete/<str:id>', views.delete_response, name='delete_response_message'),
    path('register', views.register, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),

]

website/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = models.CharField(max_length=100, unique=True)
    USERNAME_FIELD = 'username'
class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
class Message(models.Model):

    title = models.CharField(max_length=255)
    content = models.CharField(max_length=1000)
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE, default="missing_author")
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)



class Response(models.Model):
    content = models.CharField(max_length=900)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="missing_author")

website/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from website.models import Message, User, Category, Response


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['title', 'content', 'category']
        widgets = {
            "content": Textarea(attrs={"cols": 30, "rows": 4})

        }
    category = forms.ModelChoiceField(queryset=Category.objects.all())


class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ['content']
class RegisterForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

website/api/views.py
from django.contrib.auth import authenticate
from django.shortcuts import redirect
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from website.api.serializers import MessageSerializer
from website.models import Message, Category, User


@api_view(['GET'])

def get_messages(request):
    messages = Message.objects.all()
    serialized_messages = MessageSerializer(messages, many=True)

    return Response(serialized_messages.data)

@api_view(['GET'])
def get_message(request, id):
    message = Message.objects.get(id=id)
    serialized_message = MessageSerializer(message, many=False)

    return Response(serialized_message.data)


@permission_classes([IsAuthenticated])
@api_view(['POST'])
def create_message(request):
    if request.method == 'POST':
        newMessage = Message()
        user = request.user.id
        newMessage.author = User.objects.get(id=user)
        message = MessageSerializer(instance=newMessage, data=request.data)

        if message.is_valid():
            message.save()
            return Response(message.data)
    return Response('error')

@permission_classes([IsAuthenticated])
@api_view(['PUT', 'PATCH'])
def update_Message(request, id):
    if request.method == 'PUT' or request.method == 'PATCH':
        message = Message.objects.get(id=id)
        user = request.user.id

        if message.author.id != user:
            return Response('Vous n\'êtes pas autorisé à mettre à jour ce message.')

        serializer = MessageSerializer(instance=message, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response('Erreur de validation des données')

    return Response('Méthode non autorisée')


@permission_classes([IsAuthenticated])
@api_view(['DELETE'])
def delete_Message(request,id):
    message = Message.objects.get(id=id)
    user = request.user.id

    if message and message.author.id == user:
        message.delete()
        return Response('message delete')

    return Response('Error')

website/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Message, User, Response
from .forms import MessageForm, RegisterForm, ResponseForm


def index(request):

    context = {
        "message": "coucou"
    }
    return render(request, 'website/home.html', context)

def all_messages(request):
    messages = Message.objects.all()
    context = {"messages": messages}

    return render(request, 'website/all.html', context)
@login_required(login_url='login')

def new_message(request):
    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.author = request.user
            message.save()
            return redirect('show_message', message.id)


    return render(request, 'website/new_message.html',{'form' : form})

def show_message(request, id):
    message = Message.objects.get(id=id)
    responseForm = ResponseForm()
    return render(request, 'website/show.html', {"message": message, "responseForm": responseForm})

@login_required(login_url='login')
def delete_message(request, id):
    Message.objects.filter(id=id).delete()
    if Message.author != request.user:
        return redirect('all_messages')
    return redirect('all_messages')

@login_required(login_url='login')
def edit_message(request, id):
    message = Message.objects.get(id=id)
    if message.author != request.user:
        return redirect('all_messages')
    form = MessageForm(instance=message)
    if request.method == 'POST':
        form = MessageForm(data=request.POST, instance=message)
        if form.is_valid():
            message = form.save(commit=False)
            message.save()
            return redirect('show_message', message.id)
    return render(request, 'website/edit_message.html',{'form' : form,'message': message})


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        user.username = user.username.lower()
        user.set_password(user.password)
        user.save()
        return redirect('login')

    return render(request, 'website/register.html', {"form":form})


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            return redirect('all_messages')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('all_messages')

    return render(request, 'website/login.html')


def logout_user(request):
    logout(request)
    return redirect('all_messages')

@login_required(login_url='login')

def add_response(request, id):
    message = Message.objects.get(id=id)
    if message is None:
        return redirect('all_messages')
    if request.method == 'POST':
        form = ResponseForm(data=request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            response.message = message
            response.author = request.user
            response.save()

    return redirect('show_message', message.id)


@login_required(login_url='login')
def delete_response(request, id):
    response = Response.objects.get(id=id)
    if response.author != request.user:
        return redirect('all_messages')
    response.delete()
    return redirect('show_message', response.message.id)

@login_required(login_url='login')

def edit_response(request, id):
    response = Response.objects.get(id=id)
    if response.author != request.user:
        return redirect('all_messages')
    form = ResponseForm(instance=response)
    if request.method == 'POST':
        form = ResponseForm(data=request.POST, instance=response)
        if form.is_valid():
            response = form.save(commit=False)
            response.save()
            return redirect('show_message', response.message.id)

    return render(request, 'website/edit_response.html', {'form': form})

website/templates/website/all.html
{% extends 'website/base.html' %}

{% load static %}
{% block content %}


<div class="container mb-5">
<h1>Voici les messages</h1>
</div>
{% for message in messages %}
<div class="container">
<div class="border border-5 mt-5">
    <div class="text-center">

<h3>Votre Message</h3>

    <p>{{ message.title }}</p>
   <p>{{ message.content }}</p>
<a href="{% url 'show_message' message.id %}" class="btn btn-primary">voir</a>
    </div>
</div>
    </div>


{% endfor %}
{% endblock %}

website/templates/website/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
     {% load static %}
      {% load bootstrap5 %}
  {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
  {% bootstrap_javascript %}
</head>
<body>
{% include 'website/navbar.html' %}
{% block content %}

{% endblock %}

</body>
</body>
</html>

website/templates/website/edit_message.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="" class="form" method="post">
        <h3>edit message {{ message.title }}</h3>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">OK</button>
    </form>

{% endblock %}

website/templates/website/edit_response.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="mt-3">Modifier une réponse</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">VALIDER</button>
    </form>
{% endblock %}

website/templates/website/home.html
{% extends 'website/base.html' %}

{% block content %}

<p>coucou</p>



{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}

{% block content %}

    <form action="" method="post" class="form">
    {% csrf_token %}
        <div class="form-group"><input type="text" name="username" id="" class="form-control"></div>
        <div class="form-group"><input type="password" name="password" id="" class="form-control"></div>
        <button type="submit" class="btn btn-success">login</button>
    </form>


{% endblock %}

website/templates/website/navbar.html
<nav class="navbar navbar-expand-lg bg-warning">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_index' %}">Patrick</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'all_messages' %}">Messages</a>
        </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}" aria-disabled="true">Logout</a>
        </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'new_message' %}">New</a>
        </li>
                      <li class="nav-item">
          <span class="nav-link">Bonjour {{ request.user.username }}</span>
        </li>
         {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}" aria-disabled="true">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}" aria-disabled="true">Register</a>
        </li>
    {% endif %}


      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

website/templates/website/new_message.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="" class="form" method="post">
        <h3>edit message {{ message.title }}</h3>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">OK</button>
    </form>

{% endblock %}

website/templates/website/register.html
{% extends 'website/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <form action="" method="post" class="form">
    {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Register</button>
    </form>

{% endblock %}

website/templates/website/show.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="border border-5 mt-5">
    <div class="text-center">

<h3>Votre Message</h3>

        <p>category : {{ message.category.name }}</p>
    <p>{{ message.title }}</p>
   <p>{{ message.content }}</p>

        {% if request.user == message.author %}
             <a href="{% url 'delete_message' message.id %}" class="btn btn-danger">SUPPRIMER</a>
            <a href="{% url 'edit_message' message.id %}" class="btn btn-warning">EDIT</a>
        {% endif %}
    </div>
</div>
    </div>

      <hr>
    <hr>
    <div class="border border-dark">
    {% for response in message.response_set.all %}

        <div class="border border-dark">
        <p>{{ response.author.username }} wrote : </p>
            <p><strong>{{ response.content }}</strong></p>
             {% if request.user == response.author %}
            <a href="{% url 'edit_response_message' response.id %}" class="btn btn-warning">EDIT</a>
            <a href="{% url 'delete_response_message' response.id %}" class="btn btn-danger">SUPPRIMER</a>
            {% endif %}
        </div>

    {% endfor %}
    </div>
    <hr>
    <form action="{% url 'response_message' message.id %}" method="post" class="form">
    {% csrf_token %}
        {{ responseForm|crispy }}
        <button type="submit" class="btn btn-success">respond</button>
    </form>

    <hr>
{% endblock %}